---
name: Get the last 10 release tags
description: Get the last 10 release tags from github

outputs:
  latest-tag:
    description: "Returns last 10 release tags"
    value: ${{ steps.latest-tag.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: "Get last 10 tags"
      id: tags
      run: echo result=$(./.github/actions/get-tags/last-ten-tags.sh) >> "$GITHUB_OUTPUT"
      shell: bash
