---
name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment for Deployment
        required: true
        type: choice
        options:
          - staging
          - live
      action:
        description: List Revisions or Rollback
        type: choice
        options:
          - List revisions
          - Rollback
        default: List revisions
      tag:
        description: Release Number to Rollback to
        type: string
        required: false

jobs:
  list-revisions:
    name: List Revisions
    if: inputs.action == 'List revisions'
    runs-on: ubuntu-latest
#    runs-on: [ self-hosted, default ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get Tags
        id: tags
        uses: ./.github/actions/get-tags

      - name: List Previous Releases
        run: |
          echo '### List Revisions :eyes:' >> $GITHUB_STEP_SUMMARY
          echo "| Release no. | Date | Release Notes |" >> $GITHUB_STEP_SUMMARY
          echo "| :---------  | ---- | ------------- |" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.tags.outputs.tags }} >> $GITHUB_STEP_SUMMARY

  rollback:
    name:  rollback
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    timeout-minutes: 15
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display rollback version tag
        run: |
          echo "Rolling back to version: ${{ inputs.tag }}"

      - name: Check valid tag
        uses: ./.github/actions/rollback-check-tag
